import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import NavControls from '@/components/Controls'
import CreatePost from '@/components/CreatePost'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className + `
                bg-neutral-900 h-full mt-24
            `}>
                <Navbar />
                <NavControls/>
                {children}
            </body>
        </html>
    )
}
