import Navbar from "@/components/Navbar";
import "./globals.css";
import Controls from "@/components/Controls";

import { Inter } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const pretendard = localFont({
    src: "../fonts/PretendardVariable.woff2",
    display: "auto",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">
            <body
                className={
                    pretendard.className +
                    `
                bg-neutral-900 h-full mt-24 mb-20
            `
                }
            >
                <header>
                    <Navbar />
                    <Controls />
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
